NODE_FILE: ./cds_configuration_files_5.0.0/cds-model.yml
PROP_FILE: ./cds_configuration_files_5.0.0/cds-model-props.yml
SYNTHETIC_DATA_FILE: ./cds_configuration_files_5.0.0/cds-synthetic_data_values.xlsx
DATA_SPEC_FILE: ./cds_configuration_files_5.0.0/cds-mock-data-specs.yaml
ID_FILE: ./cds_configuration_files_5.0.0/props-cds.yml
OUTPUT_FOLDER: ./cds_data_files_5.0.0/
DELETE_ERROR_FILE: False
NON_PERMISSIVE_VALUE: False #Change to True if the user wants to generate non_permissive values